
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:provider/provider.dart';
import '../../core/theme/app_theme.dart';
import '../../services/cloudinary_service.dart';
import '../../core/providers/main_provider.dart';
import '../../models/data_models.dart';
import '../../services/auth_service.dart';

class UploadScreen extends StatefulWidget {
  const UploadScreen({super.key});

  @override
  State<UploadScreen> createState() => _UploadScreenState();
}

class _UploadScreenState extends State<UploadScreen> {
  final _formKey = GlobalKey<FormState>();
  final CloudinaryService _cloudinaryService = CloudinaryService();
  final AuthService _authService = AuthService();
  final ImagePicker _imagePicker = ImagePicker();
  
  File? _imageFile;
  String _title = '';
  String _description = '';
  final List<TextEditingController> _ingredientControllers = [TextEditingController()];
  final List<TextEditingController> _instructionControllers = [TextEditingController()];
  DishType _selectedType = DishType.dinner;
  bool _isUploading = false;

  @override
  void dispose() {
    for (var controller in _ingredientControllers) {
      controller.dispose();
    }
    for (var controller in _instructionControllers) {
      controller.dispose();
    }
    super.dispose();
  }

  Future<void> _pickImage() async {
    try {
      final XFile? image = await _imagePicker.pickImage(
        source: ImageSource.gallery,
        maxWidth: 1920,
        maxHeight: 1080,
        imageQuality: 85,
      );
      
      if (image != null) {
        setState(() {
          _imageFile = File(image.path);
        });
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error picking image: $e')),
        );
      }
    }
  }

  void _addIngredient() {
    setState(() {
      _ingredientControllers.add(TextEditingController());
    });
  }

  void _removeIngredient(int index) {
    if (_ingredientControllers.length > 1) {
      setState(() {
        _ingredientControllers[index].dispose();
        _ingredientControllers.removeAt(index);
      });
    }
  }

  void _addInstruction() {
    setState(() {
      _instructionControllers.add(TextEditingController());
    });
  }

  void _removeInstruction(int index) {
    if (_instructionControllers.length > 1) {
      setState(() {
        _instructionControllers[index].dispose();
        _instructionControllers.removeAt(index);
      });
    }
  }

  Future<void> _submitRecipe() async {
    if (!_formKey.currentState!.validate()) return;
    
    if (_imageFile == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please select an image')),
      );
      return;
    }

    _formKey.currentState!.save();

    final ingredients = _ingredientControllers
        .map((c) => c.text.trim())
        .where((text) => text.isNotEmpty)
        .toList();
    
    final instructions = _instructionControllers
        .map((c) => c.text.trim())
        .where((text) => text.isNotEmpty)
        .toList();

    if (ingredients.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please add at least one ingredient')),
      );
      return;
    }

    if (instructions.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please add at least one instruction')),
      );
      return;
    }

    setState(() => _isUploading = true);

    try {
      // Upload image to Cloudinary
      final imageUrl = await _cloudinaryService.uploadImage(_imageFile!);

      // Get current user
      final currentUser = _authService.currentUser;
      if (currentUser == null) {
        throw Exception('User not authenticated');
      }

      // Create user object for chef
      final chef = User(
        id: currentUser.uid,
        name: currentUser.displayName ?? 'Anonymous Chef',
        avatarUrl: currentUser.photoURL ?? 'https://i.pravatar.cc/150?u=${currentUser.uid}',
      );

      // Create recipe
      final recipe = Recipe(
        id: '', // Will be generated by Firestore
        title: _title,
        description: _description,
        imageUrl: imageUrl,
        ingredients: ingredients,
        instructions: instructions,
        type: _selectedType,
        chef: chef,
        rating: 0.0,
        reviewsCount: 0,
        isPremium: false,
      );

      // Save to Firestore
      if (!mounted) return;
      final provider = Provider.of<MainProvider>(context, listen: false);
      await provider.addRecipe(recipe);

      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Recipe uploaded successfully!')),
      );
      Navigator.pop(context);
    } catch (e) {
      if (mounted) {
        String errorMessage = 'Error uploading recipe';
        if (e.toString().contains('Cloudinary')) {
          errorMessage = 'Failed to upload image. Please try again.';
        } else if (e.toString().contains('Firestore')) {
          errorMessage = 'Failed to save recipe. Please check your connection.';
        } else {
          errorMessage = 'Error: ${e.toString()}';
        }
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(errorMessage),
            backgroundColor: Colors.red,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isUploading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Upload Recipe')),
      body: Form(
        key: _formKey,
        child: ListView(
          padding: const EdgeInsets.all(16),
          children: [
            GestureDetector(
              onTap: _pickImage,
              child: Container(
                height: 200,
                decoration: BoxDecoration(
                  color: AppColors.cardSurface,
                  borderRadius: BorderRadius.circular(16),
                  border: Border.all(color: AppColors.greyText.withValues(alpha: 0.5)),
                  image: _imageFile != null
                      ? DecorationImage(
                          image: FileImage(_imageFile!),
                          fit: BoxFit.cover,
                        )
                      : null,
                ),
                alignment: Alignment.center,
                child: _imageFile == null
                    ? const Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Icon(Icons.add_a_photo, size: 48, color: AppColors.accentOrange),
                          SizedBox(height: 8),
                          Text('Tap to add photo', style: TextStyle(color: AppColors.greyText)),
                        ],
                      )
                    : null,
              ),
            ),
            const SizedBox(height: 24),
            TextFormField(
              decoration: const InputDecoration(
                labelText: 'Recipe Title *',
                border: OutlineInputBorder(),
                filled: true,
                fillColor: AppColors.cardSurface,
              ),
              style: const TextStyle(color: Colors.white),
              onSaved: (value) => _title = value ?? '',
              validator: (value) => value?.isEmpty ?? true ? 'Please enter a title' : null,
            ),
            const SizedBox(height: 16),
            TextFormField(
              decoration: const InputDecoration(
                labelText: 'Description',
                border: OutlineInputBorder(),
                filled: true,
                fillColor: AppColors.cardSurface,
              ),
              style: const TextStyle(color: Colors.white),
              maxLines: 3,
              onSaved: (value) => _description = value ?? '',
            ),
            const SizedBox(height: 16),
            DropdownButtonFormField<DishType>(
              decoration: const InputDecoration(
                labelText: 'Dish Type',
                border: OutlineInputBorder(),
                filled: true,
                fillColor: AppColors.cardSurface,
              ),
              initialValue: _selectedType,
              items: DishType.values.map((type) {
                return DropdownMenuItem(
                  value: type,
                  child: Text(
                    type.name.toUpperCase(),
                    style: const TextStyle(color: Colors.white),
                  ),
                );
              }).toList(),
              onChanged: (value) {
                if (value != null) {
                  setState(() => _selectedType = value);
                }
              },
            ),
            const SizedBox(height: 24),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text(
                  'Ingredients *',
                  style: Theme.of(context).textTheme.titleLarge,
                ),
                IconButton(
                  icon: const Icon(Icons.add_circle, color: AppColors.accentGreen),
                  onPressed: _addIngredient,
                  tooltip: 'Add ingredient',
                ),
              ],
            ),
            ...List.generate(_ingredientControllers.length, (index) {
              return Padding(
                padding: const EdgeInsets.only(bottom: 8),
                child: Row(
                  children: [
                    Expanded(
                      child: TextFormField(
                        controller: _ingredientControllers[index],
                        decoration: InputDecoration(
                          labelText: 'Ingredient ${index + 1}',
                          border: const OutlineInputBorder(),
                          filled: true,
                          fillColor: AppColors.cardSurface,
                        ),
                        style: const TextStyle(color: Colors.white),
                        validator: (value) {
                          if (index == 0 && (value?.isEmpty ?? true)) {
                            return 'Please add at least one ingredient';
                          }
                          return null;
                        },
                      ),
                    ),
                    if (_ingredientControllers.length > 1)
                      IconButton(
                        icon: const Icon(Icons.remove_circle, color: Colors.red),
                        onPressed: () => _removeIngredient(index),
                      ),
                  ],
                ),
              );
            }),
            const SizedBox(height: 24),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text(
                  'Instructions *',
                  style: Theme.of(context).textTheme.titleLarge,
                ),
                IconButton(
                  icon: const Icon(Icons.add_circle, color: AppColors.accentGreen),
                  onPressed: _addInstruction,
                  tooltip: 'Add instruction',
                ),
              ],
            ),
            ...List.generate(_instructionControllers.length, (index) {
              return Padding(
                padding: const EdgeInsets.only(bottom: 8),
                child: Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Padding(
                      padding: const EdgeInsets.only(top: 16, right: 8),
                      child: Text(
                        '${index + 1}.',
                        style: const TextStyle(color: AppColors.accentOrange, fontSize: 16),
                      ),
                    ),
                    Expanded(
                      child: TextFormField(
                        controller: _instructionControllers[index],
                        decoration: InputDecoration(
                          labelText: 'Step ${index + 1}',
                          border: const OutlineInputBorder(),
                          filled: true,
                          fillColor: AppColors.cardSurface,
                        ),
                        style: const TextStyle(color: Colors.white),
                        maxLines: 2,
                        validator: (value) {
                          if (index == 0 && (value?.isEmpty ?? true)) {
                            return 'Please add at least one instruction';
                          }
                          return null;
                        },
                      ),
                    ),
                    if (_instructionControllers.length > 1)
                      IconButton(
                        icon: const Icon(Icons.remove_circle, color: Colors.red),
                        onPressed: () => _removeInstruction(index),
                      ),
                  ],
                ),
              );
            }),
            const SizedBox(height: 32),
            _isUploading
                ? const Center(child: CircularProgressIndicator())
                : ElevatedButton(
                    onPressed: _submitRecipe,
                    style: ElevatedButton.styleFrom(
                      backgroundColor: AppColors.accentOrange,
                      padding: const EdgeInsets.symmetric(vertical: 16),
                    ),
                    child: const Text(
                      'Submit Recipe',
                      style: TextStyle(color: Colors.white, fontSize: 18),
                    ),
                  ),
          ],
        ),
      ),
    );
  }
}
